spring.application.name=backend

# Base de datos Oracle
spring.datasource.url=${DB_URL:jdbc:oracle:thin:@//localhost:1521/FREEPDB1}
spring.datasource.username=${DB_USER:cineaustral}
spring.datasource.password=${DB_PASSWORD:1234}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# CORS configurable
cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:5173,http://localhost:3000,http://localhost:80,http://localhost}

#Puerto
server.port=8080

#Imagenes
app.upload.dir=uploads/imagenes

#TMDB API
tmdb.api.key=8e94dec55e39c721e6b8d4d4b97db924