-- =======================================================
-- CineAustral: Esquema DDL para Oracle Database (19c/21c/23ai)
-- =======================================================

-- 1. Tabla de Usuarios
CREATE TABLE usuarios (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(255) NOT NULL,
    apellido VARCHAR2(255) NOT NULL,
    email VARCHAR2(255) NOT NULL UNIQUE,
    password VARCHAR2(255) NOT NULL,
    rol VARCHAR2(50) NOT NULL
);

-- 2. Tabla de Salas
CREATE TABLE salas (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(255) NOT NULL,
    estado VARCHAR2(50) NOT NULL
);

-- 3. Tabla de Asientos
CREATE TABLE asientos (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fila VARCHAR2(10) NOT NULL,
    numero NUMBER(5) NOT NULL,
    asiento_estado VARCHAR2(50) NOT NULL,
    sala_id NUMBER NOT NULL,
    CONSTRAINT fk_asientos_sala FOREIGN KEY (sala_id) REFERENCES salas(id) ON DELETE CASCADE
);

-- 4. Tabla de Películas
CREATE TABLE peliculas (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR2(255) NOT NULL,
    genero VARCHAR2(255),
    sinopsis CLOB,
    duracion_minutos NUMBER(5) NOT NULL,
    puntuacion NUMBER(3,1),
    clasificacion VARCHAR2(50),
    imagen_url VARCHAR2(500),
    en_cartelera NUMBER(1) DEFAULT 1 NOT NULL
);

-- 5. Tabla de Funciones
CREATE TABLE funciones (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    estado VARCHAR2(50) DEFAULT 'ACTIVA' NOT NULL,
    fecha_hora_inicio TIMESTAMP NOT NULL,
    duracion_minutos NUMBER(5) NOT NULL,
    precio_por_asiento NUMBER(10,2) NOT NULL,
    pelicula_id NUMBER NOT NULL,
    sala_id NUMBER NOT NULL,
    CONSTRAINT fk_funciones_pelicula FOREIGN KEY (pelicula_id) REFERENCES peliculas(id),
    CONSTRAINT fk_funciones_sala FOREIGN KEY (sala_id) REFERENCES salas(id)
);

-- 6. Tabla de Reservas
CREATE TABLE reservas (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_reserva TIMESTAMP NOT NULL,
    precio_total NUMBER(10,2) NOT NULL,
    reserva_estado VARCHAR2(50),
    funcion_id NUMBER NOT NULL,
    cliente_id NUMBER NOT NULL,
    CONSTRAINT fk_reservas_funcion FOREIGN KEY (funcion_id) REFERENCES funciones(id),
    CONSTRAINT fk_reservas_cliente FOREIGN KEY (cliente_id) REFERENCES usuarios(id)
);

-- 7. Tabla Detalle de Reserva
CREATE TABLE detalle_reserva (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reserva_id NUMBER,
    asiento_id NUMBER,
    CONSTRAINT fk_detalle_reserva FOREIGN KEY (reserva_id) REFERENCES reservas(id) ON DELETE CASCADE,
    CONSTRAINT fk_detalle_asiento FOREIGN KEY (asiento_id) REFERENCES asientos(id)
);

-- Índices recomendados en Oracle para Foreign Keys (evita table locks en transacciones)
CREATE INDEX idx_asientos_sala ON asientos(sala_id);
CREATE INDEX idx_funciones_pelicula ON funciones(pelicula_id);
CREATE INDEX idx_funciones_sala ON funciones(sala_id);
CREATE INDEX idx_reservas_funcion ON reservas(funcion_id);
CREATE INDEX idx_reservas_cliente ON reservas(cliente_id);
CREATE INDEX idx_detalle_reserva ON detalle_reserva(reserva_id);
CREATE INDEX idx_detalle_asiento ON detalle_reserva(asiento_id);
